<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="vikram-PC" name="assertExample.VerifyTitleExample" tests="2" failures="1" timestamp="15 Jan 2018 11:43:09 GMT" time="8.274" errors="0">
  <testcase name="beforeMethod" time="8.274" classname="assertExample.VerifyTitleExample">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [ICICI Lombard: Online General Insurance Company in India | Buy Motor, Health, Travel &amp; Home Insurance] but found [ICICI Lombard: Online General Insurance Company in India | Buy Motor, Health, Travel &amp;  ]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [ICICI Lombard: Online General Insurance Company in India | Buy Motor, Health, Travel & Home Insurance] but found [ICICI Lombard: Online General Insurance Company in India | Buy Motor, Health, Travel &  ]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at assertExample.AssertExmp.asertExmp(AssertExmp.java:18)
	at assertExample.VerifyTitleExample.beforeMethod(VerifyTitleExample.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:599)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- beforeMethod -->
  <testcase name="f" time="0.000" classname="assertExample.VerifyTitleExample">
    <skipped/>
  </testcase> <!-- f -->
</testsuite> <!-- assertExample.VerifyTitleExample -->
